---
title: "Final Project Report"
author: "Jerry Albert Mathew"
date: "2026-03-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Topic: Economic Policy Uncertainty and Asset Decoupling

Student: Jerry Albert Mathew, Course: Data Mining and LLMs (Spring 2026), Lecturer: Dr. Andrea De Angelis

## Project Goal

The primary objective of this project is to investigate the relationship between economic policy uncertainty and asset decoupling. We aim to analyze how fluctuations in economic policy uncertainty impact the correlation between Gold and Nas100. By utilizing data mining techniques and large language models (LLMs), we will explore patterns and trends in financial markets to understand the extent to which economic policy uncertainty contributes to asset decoupling.

## Research Question

To what extent does high Economic Policy Uncertainty (EPU) drive a "decoupling" between the Nasdaq 100 and Gold and what specific institutional events drive these shifts?

## Data access pipeline and Methodology

1.Quantitative Analysis:Historical data on Gold prices, and Nasdaq 100 index values was retrieved using the tidyquant package which demonstrartes automated data retrieval.

2.Economic Policy Uncertainty Index: The EPU index was sourced from the FRED Api, which provides a comprehensive measure of economic policy uncertainty based on newspaper coverage. This was integrated with the financial data to analyze correlations and trends.

3.LLM Analysis: Gemini 3 Flash API was accessed to retrieve historical institutional contexts for top 3 crash dates.

## Step by Step Methodology

1)Api Access: We utilized the tidyquant package to access historical price data for Gold and the Nasdaq 100 index. The FRED API was used to retrieve the Economic Policy Uncertainty (EPU) index data.

2)Gitignore was used so that the personal Api keys wont get shared with other collaborators while sharing the work in github.

3)Packages like tidyverse,tidyquant and fredr are loaded.

4)EPU, gold and nas100 data is pulled and refined in such a way that data from 2020-01-01 is captured and is merged to a new folder named "data/final_df".

5)The data obtained from "final_df" is being mutated so that all the values are in the numeric format whirmat which is easier for further analysis.As comparing 200 point EPU to NAS100 and Gold is not a good approach for comparison, Log returns are used. Roll package is loaded for getting the 30 day rolling correlation. To obtain a plot showing the relationship between rolling correlation and EPU index, ggplot is used. The plot is saved as "plot/friction_correlation_plot" and the analysis result is saved as "data/analysis_results.csv".

6)The lowest correlation is then identified to find the top dates which have the highest decoupling rates and is then saved as "data/crash_dates.csv".

7)Gemini AI API is used and a custom R function is created get_gemini_context(), to automate the historical context for each specific crash dates.

8)The API is prompted to act as an historian to identify major US political or institutional events that contributed to economic policy uncertainity on each target date and to explain the theoretical reasons for the observed Gold and Nasdaq 100 decoupling.

9)Following the principles of reproducible workflows, a tryCatch() block was included in the script to ensure that individual API status errors would not stop the entire data-processing loop. During this phase, a hurdle was encountered where specific model versions returned 404 Not Found errors and it was resolved by transitioning to the gemini-flash-latest endpoint. The execution is done with 1 second delay to avoid rate limits.

10)The AI generated summaries are merged with the original table and is saved as "data/llm successful_explanation.csv"

11)The Final part of the project is to combine the market data with the LLM's qualitative analysis and this is done using the function "left_join".

12)Automated categorization of market behaviour is made and two categories which shows the safe heaven decoupling and liquidity crisis is categorized. This is saved as "data/final_synthesis_report"

13)Decoupling dashboard is made as a plot using ggplot and ggrepel function. The LLM generated text is also being shown there.The plot is saved as "plot/Rplot".

## Results and Analysis of Crash Dates and LLM Explanation

This section provides the qualitative reason(LLM explanation) behind the quantitative analysis(Top crash dates) by using the Gemini API. Historical and political context for the three most significant decoupling events were obtained using the Gemini API. These summaries treat the dates as historical milestones of institutional and political uncertainity.

a)27th May 2025- "Memorial Day Meltdown"\\

Quantitative Analysis- Nas100 displayed paradoxical resilience before a late-session divergence, while Gold surged by 3.2%, breaking the \$2,800/oz barrier.

Institutional drivers- The LLM analysis identifies three different institutional events converged together(Triple threat) to create a policy opacity.The Failure of the Debt Alignment Act,The Fed Independence Challenge and Silicon Sovereignty(executive order) are the three events that led to the shock.

Decoupling Analysis-This date represents a "Point of No Return" for mid-decade fiscal policy. The EPU Index spiked as the market moved from a "soft landing" narrative to a fear of fiscal dominance, where the central bank is perceived to subordinate inflation targets to fund government deficits.

Insight-Gold transitioned from a mere inflation hedge to a sovereign credit hedge Investors fled to Gold not due to consumer prices, but due to "Institutional Decay." Conversely, the Nasdaq 100 was briefly treated as a "private-sector safe haven," with investors reasoning that Big Tech balance sheets were more reliable than G20 central bank reserves.

b)28th May 2025 -"May Pivot of Uncertanity"

Quantitative Analysis- Gold rise a violent 3.2% to record high whereas the Nas100 went to a negative 4.1%

Institutional drivers- Two primary catalysts emerged: a stark U.S. Treasury warning regarding the exhaustion of "Extraordinary Measures" (the debt ceiling "X-Date") and the implementation of restrictions on the Level 5 Autonomous Systems.

Decoupling Analysis-This event is categorized as a "Flight from Systemic Risk into tangible Value".The market correctly anticipated Financial Repression,a policy of keeping interest rates lower than the inflation to melt away national debt.

Insight-The Nasdaq 100 suffered because it is considered as a "Hyper-Institutional" asset, which relies on global trade stability and predictable intellectual property laws. When the U.S. Treasury,the pillar of global finance shook, the "Digital Sovereignty" restrictions erased global revenue streams from forward-looking models, causing massive valuation compression.

c)29th May 2025-"Debt servicing Impasse"

Quantitative Analysis- Gold and Nas100 both had a rare simultaneous rise with gold having a 3.2% rise and Nas100 with a 2.1% rise and this defines the standard inverse relationship

Institutional drivers-The primary driver was the collapse of the Bipartisan Budget Act of 2025 and rumors of a Federal Reserve "Stealth Pivot"toward Yield Curve Control to manage interest payments on sovereign debt.

Decoupling Analysis-This date marks the beginning of the "Great Divergence." The standard "risk on/risk off" script failed because both assets benefited from an expected expansion of the Federal Reserve’s balance sheet (liquidity injection).

Insight-Gold acted as a "Sovereign Credit Default Swap" against the failure of the U.S. Treasury. Simultaneously, the Nasdaq was viewed as a productivity lifeboat. Investors reasoned that even if the government faced fiscal instability, private sector AI innovation remained insulated. This formed a new market alliance: the anti fragile barbell,where investors held assets the government could not print (Gold) and entities that could outrun mismanagement through innovation (Nas100)

## Critical reflection on limitations and validity

LLM's are used as a supervisor for the project. I encountered "http 404" errors when using the Gemini API for the LLM explanation. Even after trying to solve using LLM it wasnt working properly and in my further research I solved the problem by not showing the specific gemini model, instead the latest model was used and this solved the problem.

The final analysis is not very usefull with the current research results.I think more analysis on the explanation given by the LLM should be done. The analysis should be made more broad with having a higher decoupling dates for analysis.The LLM explanation should also be constructed into some scale for a better comparitive analysis.

## GitHub Process and Documentation

The project shows an iterative development model which shows the whole process step by step-

The github repository is divided into folders -

1)"/data" which shows all the data sets being produced and is saved as csv files.

2)"/plot" which shows the two plots being made in the project.

3)"/scripts" which shows all the scripts being written and saved in that order

4)".gitignore" is there to have a privacy over the API keys

5)"Data_Mining_Project.Rproj" is a trial R project which I used as a test for using github repository.

6)"README.md" is the readme file and is being uploaded into the repository.

7)"Project report.Rmd" is this file and is the final folder in the repository.

## LLM Disclosure

Gemini 3 Flash is used via API for the LLM generated texts. ChatGPT and Gemini are also being used for writing and debugging the codes. The code for getting the historical and political contexts using Gemini API was fully constructed using LLM. Most of the other codes were written by myself eventhough it was perfected using LLM's.
